import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Main from "./components/home/main";

import Layout from "./components/layout";

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>윤건호 노션 포트폴리오</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex min-h-screen flex-col items-center justify-center text-gray-600 body-font">
        <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
          <Main />
        </div>
      </section>
    </Layout>
  );
};

export default Home;

// pages의 index는 무조건 root이다
